[tool.poetry]
name = "unblob"
version = "23.1.30"
description = "Extract files from any kind of container formats"
authors = ["ONEKEY <support@onekey.com>"]
license = "MIT"
packages = [
    { include = "unblob" },
]
include = ["rust/*", "rust/src/*"]
build = "build.py"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
"dissect.cstruct" = "^2.0"
attrs = "^22.2.0"
structlog = "^21.2.0"
arpy = "^2.2.0"
rarfile = "^4.0"
ubi-reader = "^0.8.5"
python-lzo = "^1.14"
yaffshiv = { git = "https://github.com/onekey-sec/yaffshiv.git", rev = "a8f21283c25057740371fd34e9b6f3c4771375f1" }
plotext = ">=4.2.0,<6.0"
pluggy = "^1.0.0"
python-magic = "^0.4.27"
pyperscan = "^0.2.0"
lark = "^1.1.2"
lz4 = "^4.0.0"
lief = "^0.12.3"
jefferson = "^0.4.2"
cryptography = ">=37.0.1,<40.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.4"
pyright = "^0.0.12"
pre-commit = "^2.15.0"
pytest-cov = "^3.0.0"
setuptools-rust = "^1.1.2"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs-material = "8.5.10"
mkdocstrings = "^0.19.1"
pillow = "^9.4.0"
cairosvg = "^2.7.0"
mkdocstrings-python = "^0.8.3"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
unblob = "unblob.cli:main"

[tool.pytest.ini_options]
addopts = "--cov=unblob --cov=tests --cov-branch --cov-fail-under=90"
norecursedirs = """
  *.egg
  *_extract
  .*
  dist
  build
  target
  tests/integration
"""

[tool.vulture]
paths = ["unblob/", "vulture_whitelist.py" ]
exclude = ["unblob/_py/", "unblob/testing.py"]

[tool.pyright]
exclude = ["build"]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=60.9.3", "setuptools-rust==1.5.1"]
build-backend = "poetry.core.masonry.api"
