[tool.poetry]
name = "unblob"
version = "0.1.0"
description = "Extract files from any kind of container formats"
authors = ["IoT Inspector <support@iot-inspector.com>"]
license = "MIT"
packages = [
    { include = "unblob" },
]

[tool.poetry.dependencies]
python = "^3.8"
yara-python = "^4.1.0"
click = "^8.0.1"
"dissect.cstruct" = "^2.0"
typing-extensions = "^4.0.0"
attrs = "^21.2.0"
structlog = "^21.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.10b0"
isort = "^5.10.1"
pyright = "^0.0.12"
flake8 = "^4.0.1"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
unblob = "unblob.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
