name: Build Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  DOCKER_IMAGE: ghcr.io/onekey-sec/unblob:latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup git lfs
        uses: ./.github/actions/setup-git-lfs

      - name: Setup 3rd party dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Poetry build
        run: poetry build --format wheel

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Check unblob - help
        run: docker run --rm ${{ env.DOCKER_IMAGE }} --help

      - name: Check unblob - show-external-dependencies
        run: docker run --rm ${{ env.DOCKER_IMAGE }} --show-external-dependencies

      - name: Check unblob - run for a file with --verbose
        run: docker run --rm -v "$(pwd)"/tests/integration/archive/zip/regular:/test ${{ env.DOCKER_IMAGE }} -v -e /tmp /test/__input__/apple.zip

      - name: Build and push
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
