name: Rust Binding

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.lock'
      - 'rust/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'Cargo.lock'
      - 'rust/**'


jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.60.0

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo audit
        uses: actions-rust-lang/audit@v1

      - name: Run cargo test
        run: cargo test

      - name: Build cargo bench
        run: cargo bench --no-run
